global using System;
global using System.Diagnostics.CodeAnalysis;
global using System.IO;
global using System.Threading;
global using SecretLabNAudio.YouTube.Exceptions;
global using UnityEngine;
global using YoutubeExplode;
global using YoutubeExplode.Exceptions;
global using YoutubeExplode.Videos;
global using YoutubeExplode.Videos.Streams;
global using SaveCacheResult = (string OutputPath, SecretLabNAudio.FFmpeg.Caches.SaveCacheError? Error);
